spring:

  profiles:
    active: local

  h2:
    console:
      enabled: true


  # temp db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database-platform:
#    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
    defer-datasource-initialization: true

  jwt:
    header: Authorization
    secret: APPLE1BANANA2CIRCLE3DIAMOND4ELITE5FLY6GRANT7HYBERNATE8
    access-token-validity-in-seconds: 180000
    refresh-token-validity-in-seconds: 604800

  cache:
    type: redis

  redis:
    host: localhost
    port: 6390

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      file-size-threshold: 1MB
      location: D:/workspace/A-SIDER-back/files
      max-file-size: 100MB
      max-request-size: 100MB

api:
  v1: /api/v1

# Logging
logging:
  level:
    org.hibernate.type: trace
    org.springframework: info
